apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'com.vanniktech.maven.publish'
apply plugin: 'org.jetbrains.dokka'

dependencies {
  api projects.retrofit
  api projects.retrofitAdapters.sse.core
  api libs.okhttp.sse
  compileOnly libs.findBugsAnnotations

  testImplementation libs.junit
  testImplementation libs.truth
  testImplementation libs.guava
  testImplementation libs.okhttp.mockwebserver
  testImplementation projects.retrofitConverters.scalars
  testImplementation projects.retrofitConverters.gson
}

jar {
  manifest {
    attributes 'Automatic-Module-Name': 'retrofit2.adapter.sse-java9'
  }
}

kotlin {
  jvmToolchain 9
}
