apply plugin: 'java-library'
apply plugin: 'com.vanniktech.maven.publish'

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}


dependencies {
  api projects.retrofit
  api libs.jackson3Databind
  compileOnly libs.findBugsAnnotations

  testImplementation libs.junit
  testImplementation libs.truth
  testImplementation libs.okhttp.mockwebserver
  testImplementation libs.testParameterInjector
  testImplementation libs.jackson3DataformatCbor
}

jar {
  manifest {
    attributes  'Automatic-Module-Name': 'retrofit2.converter.jackson3'
  }
}
