apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'com.vanniktech.maven.publish'

def addExtraSourceSet(String name) {
  def sourceSet = sourceSets.create(name) {
    java.srcDir("src/main/$name")
  }

  // Propagate dependencies to be visible to this source set.
  configurations.getByName("${name}Implementation").extendsFrom(configurations.getByName('implementation'))
  configurations.getByName("${name}Api").extendsFrom(configurations.getByName('api'))
  configurations.getByName("${name}CompileOnly").extendsFrom(configurations.getByName('compileOnly'))

  return sourceSet
}

def addMultiReleaseSourceSet(int version) {
  def name = "java${version}"
  def sourceSet = addExtraSourceSet(name)

  // Allow types in the main source set to be visible to this version's source set.
  dependencies.add("${name}Implementation", sourceSets.getByName("main").output)

  tasks.named("compileJava${version}Java", JavaCompile) {
    javaCompiler = javaToolchains.compilerFor {
      languageVersion = JavaLanguageVersion.of(version)
      vendor = JvmVendorSpec.AZUL
    }
  }

  tasks.named('jar', Jar) {
    from(sourceSet.output) {
      into("META-INF/versions/$version")
    }
  }
}

addMultiReleaseSourceSet(14)
addMultiReleaseSourceSet(16)

def extra = addExtraSourceSet('extra')

dependencies {
  api libs.okhttp.client

  compileOnly extra.output
  compileOnly libs.android
  compileOnly libs.kotlinx.coroutines

  compileOnly libs.animalSnifferAnnotations
  compileOnly libs.findBugsAnnotations
}

javadoc {
  exclude('retrofit2/internal/**')
}

tasks.named('jar', Jar) {
  from(extra.output)

  manifest {
    attributes 'Automatic-Module-Name': 'retrofit2'
    attributes 'Multi-Release': 'true'
  }
}
