name: build

on:
  pull_request: {}
  push:
    branches:
      - 'trunk'

jobs:
  jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Run checkstyle
      - uses: actions/setup-java@v4
        name: Run JDK
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version

      - name: Test
        run: echo "create a folder